# Generated by Django 2.2.14 on 2020-09-28 10:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_address_phone_numeber'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='address',
            name='phone_numeber',
        ),
        migrations.RemoveField(
            model_name='item',
            name='available_quantity',
        ),
        migrations.RemoveField(
            model_name='item',
            name='discount_percentage',
        ),
        migrations.RemoveField(
            model_name='item',
            name='do_we_sell',
        ),
        migrations.RemoveField(
            model_name='item',
            name='manufacturer',
        ),
    ]
