# Generated by Django 2.2.14 on 2020-09-28 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20200928_1538'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='address',
            name='country',
        ),
        migrations.AddField(
            model_name='address',
            name='city_address',
            field=models.CharField(default='Lucknow', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='address',
            name='customer_mobile',
            field=models.CharField(default='1111111111', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='address',
            name='customer_name',
            field=models.CharField(default='shiva', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='address',
            name='landmark_address',
            field=models.CharField(default='chowki', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='address',
            name='locality_address',
            field=models.CharField(default='aligank', max_length=100),
            preserve_default=False,
        ),
    ]
