# Generated by Django 2.2.14 on 2020-10-02 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20200928_2258'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='address_of_order',
            field=models.CharField(default='complete', max_length=100),
            preserve_default=False,
        ),
    ]
