# Generated by Django 2.2.14 on 2020-10-02 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_order_address_of_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='prescription',
            field=models.BooleanField(default=False),
        ),
    ]
