# Generated by Django 2.2.14 on 2020-10-02 19:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_item_prescription'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='prescription',
        ),
    ]
