# Generated by Django 2.2.14 on 2020-10-03 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_order_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='bill_no',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
