# Generated by Django 2.2.14 on 2020-10-07 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_orderitem_bill_no'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='order_cancelled',
            field=models.BooleanField(default=False),
        ),
    ]
